In [3]:
''' NumPy is a Pyhton library.
NumPy is used for working with arrays.
NumPy is short for "numerical python".
NumPy aims to provide an array object that is up to 
50x faster then traditional python lists.

The array object in NumPy is called ndarray,
it provides a lot of supporting functions that make working with ndarray very easy.
'''

import numpy

arr=numpy.array([1,2,3,4,5]) #variable name=arr

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
''' create an alias with the keyword as while importing '''

import numpy as np #numpy package can be referred to as np instead of numpy

arr= np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


In [6]:
import numpy as np
print(np.__version__)

1.26.4


In [7]:
import numpy as av
print(av.__version__)

1.26.4


In [8]:
import numpy as np

arr=np.array((1,2,3,4,5))
print(arr)



[1 2 3 4 5]


In [9]:
#create an 1-D array containing the values 1,2,3,4,5

import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
#create a 2-D array containing two arrays with values 1,2,3 and 4,5,6

arr=np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
#create  a 3-D array with two 2-D array
#both containing two array with the values 1,2,3 and 4,5,6

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
'''NumPy arrays provide the ndim attribute that returns an integer 
that tells us how many dimensions the array have.'''

#check how many dimensions the array have:

a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
#access the element on the first row, second column:

import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  2


In [16]:
#sort the array

import numpy as np

arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]
